RetryUtil: handle task cancel when RefreshPlayListAsync timeout
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.